const levelLabels=Object.fromEntries(levels.map(([code,cn])=>[code,cn]));
let selectedLevel='A1',selectedTopic='全部';
const homeSearch=document.getElementById('search');
function safe(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function visibleArticles(){const q=homeSearch.value.trim().toLowerCase();return articles.filter(a=>a.level===selectedLevel&&(selectedTopic==='全部'||a.topic===selectedTopic)&&`${a.title} ${a.subtitle} ${a.topic}`.toLowerCase().includes(q))}
function renderLevels(){document.getElementById('levels').innerHTML=levels.map(([code,cn,en])=>`<button class="level ${code===selectedLevel?'active':''}" data-level="${code}"><b>${code}</b><span>${cn} · ${en}</span></button>`).join('');document.querySelectorAll('.level').forEach(button=>button.onclick=()=>{selectedLevel=button.dataset.level;selectedTopic='全部';renderLibrary()})}
function renderTopics(){const topics=['全部',...new Set(articles.filter(a=>a.level===selectedLevel).map(a=>a.topic))];document.getElementById('filters').innerHTML=topics.map(topic=>`<button class="chip ${selectedTopic===topic?'active':''}" data-topic="${safe(topic)}">${safe(topic)}</button>`).join('');document.querySelectorAll('.chip').forEach(button=>button.onclick=()=>{selectedTopic=button.dataset.topic;renderLibrary()})}
function renderArticles(){const data=visibleArticles();document.getElementById('articleCount').textContent=`${articles.filter(a=>a.level===selectedLevel).length} 篇短文`;document.getElementById('articleGrid').innerHTML=data.length?data.map(a=>`<article class="article-card"><div class="article-cover"><img src="images/covers/${encodeURIComponent(a.id)}.svg" alt="${safe(a.title)}主题插画" loading="lazy"><span class="cover-level">${safe(a.level)} · CEFR</span></div><div class="article-card-body"><div class="card-top"><span class="topic-tag">${safe(a.topic)}</span><span class="card-time">约 ${a.mins} 分钟</span></div><h3><a class="article-title-link" href="article.html?id=${encodeURIComponent(a.id)}" target="_blank" rel="noopener">${safe(a.title)}</a></h3><div class="title-cn">（${safe(a.subtitle)}）</div><div class="card-bottom"><span>${a.text.split(/\s+/).length} 词 · ${safe(a.level)} 阅读</span><span class="card-arrow" aria-hidden="true">↗</span></div></div></article>`).join(''):'<div class="empty">没有找到相关短文，试试其他主题或关键词。</div>'}
function renderLibrary(){renderLevels();renderTopics();renderArticles()}
homeSearch.addEventListener('input',renderArticles);
renderLibrary();
